// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7RfpifhCneaW6o_s6HfGg2gcy6FExSM',
    appId: '1:480647790824:web:b3e7e18b4279ce6e8e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    authDomain: 'expanse-tracker-app-2d7e4.firebaseapp.com',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
    measurementId: 'G-KSM03RPBCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQzd36H8cGjQM_7Bb3fhXPCF8BHbEaaY',
    appId: '1:480647790824:android:c73c3b574855ecf78e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sSt-ojRR4r64jYJUfDLrhEgJaFnX2j0',
    appId: '1:480647790824:ios:510acd789fc2f0ca8e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
    androidClientId: '480647790824-id9c88rcuh764bng3ij5ccnmra6dn83j.apps.googleusercontent.com',
    iosClientId: '480647790824-j9fuvukb5d22vbeg180gclaquq8h62g7.apps.googleusercontent.com',
    iosBundleId: 'com.kesava.expanseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3sSt-ojRR4r64jYJUfDLrhEgJaFnX2j0',
    appId: '1:480647790824:ios:783606a2c50557218e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
    androidClientId: '480647790824-id9c88rcuh764bng3ij5ccnmra6dn83j.apps.googleusercontent.com',
    iosClientId: '480647790824-1hdll7io52hme49icou6o5rgnd1al330.apps.googleusercontent.com',
    iosBundleId: 'com.example.expanseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7RfpifhCneaW6o_s6HfGg2gcy6FExSM',
    appId: '1:480647790824:web:1d96fb5a6a282bfe8e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    authDomain: 'expanse-tracker-app-2d7e4.firebaseapp.com',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
    measurementId: 'G-2TCHQ2BH06',
  );
}
