platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  File.expand_path('/Users/app/Downloads/flutter', __FILE__)
end

require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  use_frameworks! :linkage => :static   # ✅ Best for Firebase
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # ✅ Force all pods to use iOS 13.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
